### ISSUE TITLE
SQL interpolation behaviour for various parameter types should be documented

### ISSUE THREAD

**Issue by admackin** [scalikejdbc/scalikejdbc.github.io#33]
Documentation is very boring, but it would be great to have some notes on the SQLInterpolation page about how various passed-in parameter types will be handled. Obviously scalikejdbc knows how to handle particular types. In particular, it seems that numeric types and strings behave exactly as expected. In addition, I know that Scala collection types are converted into a comma-separated list (I've used them, and I still can't remember if wrapping parentheses are added though!). I also think that `java.util.Date` is handled correctly, as is `org.joda.DateTime`. Presumably these are special-cased.  But what about other classes? What is the algorithm for working out how an instance will be converted to SQL?

I might hope that `Option` instances would be handled sensibly (wrapped value used if it's `Some`; SQL `null` for `None`). I'm still not sure how 'unknown' classes are handled – does it simply call `.toString()`?

I could presumably work most of this out by browsing through the source, but in general library users shouldn't be expected to do this for a fairly important feature.

**Comment by admackin** [comment]
Pull request #34 attempts to address this

**Comment by seratch** [comment]
Thank you for your great contribution. The pull request looks good to me.

>I'm still not sure how 'unknown' classes are handled – does it simply call .toString()?

As you described at #34, unknown type values are just passed as a java.lang.Object to the PreparedStatement. https://github.com/scalikejdbc/scalikejdbc/blob/2.3.4/scalikejdbc-core/src/main/scala/scalikejdbc/StatementExecutor.scala#L114-L116

**Comment by seratch** [comment]
Thanks to #34, we can close this issue now.
