### ISSUE TITLE
auto deploy from develop to master branch use travis-ci and github deploy key?

### ISSUE THREAD

**Issue by xuwei-k** [scalikejdbc/scalikejdbc.github.io#47]
- http://xuwei-k.hatenablog.com/entry/20151126/1448537637
- http://blog.eiel.info/blog/2014/02/18/github-push-from-travis/
- http://eed3si9n.com/auto-publish-from-travis-ci

**Comment by seratch** [comment]
Sounds good.

**Comment by xuwei-k** [comment]
@seratch could you give me the admin authority of this repository? I want to register a deploy key.

**Comment by seratch** [comment]
@xuwei-k Sorry for my late reply. I just changed your role in the organization to Owner.

**Comment by xuwei-k** [comment]
done (๑•̀ㅂ•́)و✧

should we delete https://github.com/scalikejdbc/scalikejdbc.github.io/blob/develop/deploy_to_ghpages.sh ?

**Comment by seratch** [comment]
Thanks!

>should we delete https://github.com/scalikejdbc/scalikejdbc.github.io/blob/develop/deploy_to_ghpages.sh ?
Yes, please.
