### ISSUE TITLE
TxBoundary example for an IO monad doesn't work with cats-effect

### ISSUE THREAD

**Issue by matil019** [scalikejdbc/scalikejdbc.github.io#97]
Nice to meet you!

The `TxBoundary` example for a hand-made IO monad in [the official documentation](http://scalikejdbc.org/documentation/transaction.html#working-with-io-monads) doesn't work with `cats.effect.IO` if applied verbatim; `finishTx` would execute `result` twice (because `cats.effect.IO` doesn't memoize), and `closeConnection` isn't exception-safe. Overall, it appears to be written with eager and memoizing monads (such as `Future`) in mind.

Fortunately, no changes to the library code are needed to make it work. I was able to create a working `TxBoundary` for `cats.effect.IO`:

```scala
import scalikejdbc._
import cats.effect._

implicit def catsEffectIOTxBoundary[A]: TxBoundary[IO[A]] = new TxBoundary[IO[A]] {
  def finishTx(result: IO[A], tx: Tx): IO[A] =
    result.guaranteeCase{
      case ExitCase.Completed => IO(tx.commit())
      case _ => IO(tx.rollback())
    }

  override def closeConnection(result: IO[A], doClose: () => Unit): IO[A] =
    result.guarantee(IO(doClose()))
}
```

The caveat is that `DB.localTx` itself has to be suspended in `IO` as well to correctly sequence the effects, like this:

```scala
IO.suspend {
  DB.localTx { implicit session =>
    /* IO { ... } */
  }(boundary = catsEffectIOTxBoundary)
}
```

I think I'm able to write a PR by myself but I have a question: Currently the documentation uses a hand-made monad `MyIO` but mine uses cats-effect specifics such as `IO#guaranteeCase`. (`attempt` can't be used because there are cancellations.) And the `IO.suspend` thing. Do you think it is OK to add a new example dedicated to `cats.effect.IO`, or should `MyIO` section be simply replaced with it?

**Comment by seratch** [comment]
This seems to be related to this issue: https://github.com/scalikejdbc/scalikejdbc/issues/1105

It's fine to update the document as you suggest. All document should be practical.

**Comment by matil019** [comment]
I believe the linked issue is the same one (I looked for `TxBoundary` and missed it).

I'll write a PR with @capacman's fix applied to `MyIO` so that ZIO users would also benefit from this.
